openapi: 3.0.0
info:
  title: API Gestione Note Spese ALES
  description: API REST per la gestione delle note spese con autenticazione Bearer Token.
  version: 1.0.0

servers:
  - url: https://test.diquit.it
    description: Server di produzione

tags:
  - name: Autenticazione
    description: Endpoint per l'accesso e gestione token
  - name: Note Spese
    description: Operazioni sulle note spese

paths:
  /api_ales/login:
    post:
      tags:
        - Autenticazione
      summary: Autenticazione utente
      description: Permette di ottenere un Bearer Token per autenticare le richieste successive.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Token generato con successo
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  token_type:
                    type: string
                  expires_in:
                    type: integer

  /api_ales/nota-spese/{anno}:
    get:
      tags:
        - Note Spese
      summary: Recupera tutte le note spese per un determinato anno, con mese opzionale
      parameters:
        - name: anno
          in: path
          required: true
          schema:
            type: integer
        - name: mese
          in: query
          required: false
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Elenco delle note spese
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    matricola:
                      type: string
                    data:
                      type: string
                      format: date
                    importo:
                      type: number
                    stato:
                      type: string
                    trasferta:
                      type: string

  /api_ales/nota-spese:
    get:
      tags:
        - Note Spese
      summary: Recupera la nota spese di un dipendente tramite matricola
      parameters:
        - name: matricola
          in: query
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Dettaglio della nota spese
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  matricola:
                    type: string
                  data:
                    type: string
                    format: date
                  importo:
                    type: number
                  stato:
                    type: string
                  trasferta:
                    type: string

  /api_ales/nota-spese/{id}/stato:
    put:
      tags:
        - Note Spese
      summary: Aggiorna lo stato di una nota spese
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                stato:
                  type: string
                trasferta:
                  type: string
      responses:
        '200':
          description: Stato aggiornato con successo
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  id:
                    type: integer
                  stato:
                    type: string
                  trasferta:
                    type: string

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
